### ISSUE TITLE
When attempting to run after full set up receiving "KeyError: 'accounts'.

### ISSUE THREAD

**Issue by ixl911ixl** [BoBeR182/Pokemon-Go-Bot-Working-Hack-API#16]
I have yet to get the game to successfully run on my Windows 10 Desktop.

After following all of the steps listed, 

I enter;
pokebot.py -i 0 --cache

It returns;
Traceback (most recent call last):
  File "C:\Python27\Scripts\pokebot.py", line 105, in <module>
    main()
  File "C:\Python27\Scripts\pokebot.py", line 74, in main
    config = init_config()
  File "C:\Python27\Scripts\pokebot.py", line 49, in init_config
    required=required("auth_service"))
  File "C:\Python27\Scripts\pokebot.py", line 46, in required
    return x not in load['accounts'][0].keys()
KeyError: 'accounts'

What did I miss?

**Comment by ixl911ixl** [comment]
Just in case this was wrong,

On the Google Maps API step, I copied a "Server Key" from the page that I generated. There were tons of options though (Ios Key, Browser Key, Server Key, etc.) and I had no clue which one to choose so I just choose server? Hopefully that's correct? It was a string of random characters.

**Comment by BoBeR182** [comment]
Sounds like you got it working, I will be closing this issue.
